mutation logIn($email: String!, $password: String!) {
  logInAsUser(email: $email, password: $password) {
    __typename
    ... on User {
      id
      email
      firstName
      lastName
    }
    ... on AuthenticationError {
      message
    }
  }
}
