query clientPlayersInRoom {
  roomSession {
    id
    room {
      roomSessions {
        id
        controllerNumber
        nickname
      }
    }
  }
}

query hostPlayersInRoom {
  user {
    vulcasts {
      room {
        roomSessions {
          id
          nickname
          controllerNumber
        }
      }
    }
  }
}
