query clientPlayersInRoom {
  roomSession {
    id
    room {
      id
      roomSessions {
        id
        controllerNumber
        nickname
      }
    }
  }
}

query hostPlayersInRoom {
  user {
    id
    vulcasts {
      id
      room {
        id
        roomSessions {
          id
          nickname
          controllerNumber
        }
      }
    }
  }
}

mutation SetControllerNumbersForRoomSessions(
  $roomId: ID!
  $controllerNumbersForRoomSessions: [ControllerNumberForRoomSessionInput!]!
) {
  setControllerNumbersForRoomSessions(
    roomId: $roomId
    controllerNumbersForRoomSessions: $controllerNumbersForRoomSessions
  ) {
    __typename
    ... on UpdatedRoomSessions {
      roomSessions {
        id
        controllerNumber
      }
    }
    ... on AuthenticationError {
      message
    }
  }
}
