mutation createUser(
  $email: String!
  $password: String!
  $firstName: String!
  $lastName: String!
) {
  createUser(
    email: $email
    password: $password
    firstName: $firstName
    lastName: $lastName
  ) {
    __typename
    ... on User {
      id
      email
      firstName
      lastName
    }
    ... on AuthenticationError {
      message
    }
    ... on EmailInUseError {
      message
    }
    ... on InvalidEmailError {
      message
    }
    ... on InvalidFirstNameError {
      message
    }
    ... on InvalidLastNameError {
      message
    }
    ... on InvalidPasswordError {
      message
    }
  }
}
