mutation createRoom($vulcastId: ID!) {
  createRoom(vulcastId: $vulcastId) {
    __typename
    ... on Room {
      id
      relay {
        hostName
      }
    }
    ... on AuthenticationError {
      message
    }
    ... on VulcastNotFoundError {
      message
    }
    ... on VulcastInRoomError {
      message
    }
    ... on VulcastNotAssignedToRelayError {
      message
    }
  }
}
