name: Web CD
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_static:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VULCAN_FYDP_CI_SSH_PRIVATE_KEY }}
      - run: npm ci
      - run: npm run codegen
      - run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: true
          REACT_APP_TARGET: static
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_COAST_0F2873910 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/build" # App source code path
          skip_app_build: true
          output_location: ""
          ###### End of Repository/Build Configurations ######
