name: Web CI
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VULCAN_FYDP_CI_SSH_PRIVATE_KEY }}
      - run: npm ci
      - run: npm run codegen
      - run: npm run lint:ci
  build_app:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VULCAN_FYDP_CI_SSH_PRIVATE_KEY }}
      - run: npm ci
      - run: npm run codegen
      - run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: true
          REACT_APP_TARGET: app
  build_static:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VULCAN_FYDP_CI_SSH_PRIVATE_KEY }}
      - run: npm ci
      - run: npm run codegen
      - run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: true
          REACT_APP_TARGET: static
